language: r
cache: packages
sudo: true
dist: trusty

env:
  - CODECOV_TOKEN="40f86a6d-0a11-485b-986d-385f921a73f5"

r_packages:
  - roxygen2
  - devtools
  - XML
  - yaml
  - covr
  - dplyr

script:
  - Rscript -e 'library(devtools); checkOutput <- data.frame(test()); if (sum(checkOutput["failed"]) + sum(checkOutput[["error"]]) > 0){q(status = 1, save = "no")}'

after_success:
  - Rscript -e 'library(covr); codecov()'
